### ISSUE TITLE
scons error

### ISSUE THREAD

**Issue by prulitarit** [jjackowski/screentouch#1]
When run scons in dir I get an error: 
```
scons: Reading SConscript files ...
NameError: name 'cmp' is not defined:
  File "/home/frog/Downloads/screentouch-master/SConstruct", line 132:
    Help(buildopts.GenerateHelpText(dbgenv, cmp))

```

How to compile this project?

**Comment by jjackowski** [comment]
I tried building on a Raspberry Pi again, but didn't see the problem there. I also tried on an Ubuntu system which did show the problem. I think it may have been caused by a change between Python versions 2.7.16 and 2.7.18, but I'm not sure. I committed a fix (285377e34c441fed9dda888a7fb187b3204d4a9a) that also addresses a couple other little issues I saw.

I hope that works for you!

**Comment by prulitarit** [comment]
Now scons works. Successfully built, after downgrading boost and boost-libs from 1.75 to 1.69. With boost 1.75 g++ failed with error

```
g++ -o bin/linux-x86_64-dbg/MtTranslate.o -c -std=c++17 -g -fno-common -Og -Ibin/linux-x86_64-dbg -I. -I. -I/usr/include/libevdev-1.0 MtTranslate.cpp
MtTranslate.cpp: In member function 'void MtTranslate::init()':
MtTranslate.cpp:24:46: error: '_2' was not declared in this scope
   24 |   boost::bind(&MtTranslate::slotEvent, this, _2)
      |                                              ^~

```
My config is:
os: archlinux
python: 3.9.3
gcc: 10.2.0
boost: 1.69

Many thanks.

**Comment by jjackowski** [comment]
I just did a build with another system and got that same error along with some warnings. I think I know how to solve the error, but I want to take some time to test with different versions of Boost to make sure I get something that works on the newer libraries often seen in Arch and Gentoo, and the older libraries in Raspberry Pi OS. I also want to get rid of the warnings. I might not have the time for a couple days or so.

Thanks for the feedback!

**Comment by jjackowski** [comment]
I made another commit (af86dc7c90f27c1f0e035b7ce5b093b417cd0ace) that allows me to build on Boost 1.67 to 1.75, so you shouldn't need to downgrade Boost to build anymore.

**Comment by prulitarit** [comment]
thanks! closed.
